### ISSUE TITLE
Search all available storage for patches

### ISSUE THREAD

**Issue by chr15m** [chr15m/PdDroidParty#25]
`buildPatchList` should concatenate found patches from all storage sources (`ContextCompat.getExternalFilesDirs(applicationContext, null)`)

---

Klaus says:

> i have PdDroidParty running on my Galaxy A3, Android Version 5.0.2.
> i put the test files from http://droidparty.net/ onto my sd card in a 
> folder called
> PdDroidParty but the app does not find any patches.
> 
> i only see a black screen with "PdDroidParty compatible patches found:"
> "finding patches" is performed at startup but the screen stays empty.
> i tried other locations for the pd-patches and naming the folder 
> differently according to my web-searches with no success.
> i also tried on two different phones with the same result.

**Comment by mxa** [comment]
AFAIK Android versions 4.1(?) and up only allow apps to read and save data from the SD-Card which are in their folders, which is SD-Card/Android/data/net.droidparty/ or similar

**Comment by chr15m** [comment]
Klaus reported that moving his patches to internal storage worked. I am not 100% sure what is going on but you are right about KitKat's SD card restrictions too. What a pain!

**Comment by chr15m** [comment]
Fix: check all storages after requesting permission #49.
