### ISSUE TITLE
support for bob~

### ISSUE THREAD

**Issue by robbielongcat** [chr15m/PdDroidParty#33]
bob~ is a Filter in vanilla pd, it arrived near the end of version 0.46 (current version 0.47-1). bob~ does not work in pddroidparty.

**Comment by chr15m** [comment]
Hi @robbielongcat this should be an easy fix. Update libpd submodule to the latest master and re-build the apk. I don't have a working Android build environment and I no longer build software for proprietary devices so somebody else will have to do this.

If anybody does this and submits a PR and the built apk I will merge and add it as a release.

**Comment by chr15m** [comment]
@robbielongcat this was fixed when libpd was upgraded in this project. The bob~ object now works.

**Comment by robbielongcat** [comment]
Thanks x
