### ISSUE TITLE
Set portrait mode if the patch ratio appears to be portrait

### ISSUE THREAD

**Issue by umlaeute** [chr15m/PdDroidParty#34]
it seems that only landscape mode is supported (at least if you want to use text :-))

**Comment by chr15m** [comment]
This would be a useful feature. Could be implemented as a comment in the top level patch e.g.:
 * `pdparty/orientation portrait`
 * `pdparty/orientation landscape`
 * `pdparty/orientation any`

**Comment by umlaeute** [comment]
or more simple:
- if the viewport has `w>h`: use landscape mode
- if the viewport has `h>w`: use portrait mode
- if the viewport has `w==h`: keep current mode

this has the advantage, that one could switch between landscape & portrait mode programmatically.

lacking an explicit viewport, use the main window dimension.

i think the only compat problem is, if somebody relies on the heavy distortion by the automatic rescaling.

**Comment by chr15m** [comment]
@umlaeute good idea, thanks.
