### ISSUE TITLE
Fix build against latest version of libpd

### ISSUE THREAD

**Issue by craigcomstock** [chr15m/PdDroidParty#46]
From TODO.txt

**Comment by craigcomstock** [comment]
@chr15m I checked build.gradle and it specifies in dependencies:

`implementation 'org.puredata.android:pd-core:1.1.0'`

As far as I can see from https://github.com/libpd/pd-for-android/releases 1.1.0 is the latest which says "Upgrade to PD-0.48-0". So it seems like PdDroidParty is setup to latest of pd-for-android.

I see in PdDroidParty/.gitmodules a reference to pd-for-android and in pd-for-android/.gitmodules a reference to libpd.

https://github.com/libpd/libpd/releases is at 0.11.0

I think I need to learn/document how this all fits together. :+1: Will keep looking.

**Comment by chr15m** [comment]
@craigcomstock thanks for investigating. Sounds like it's already the latest pd-for-android. Maybe we should remove the git submodule now that gradle is pulling it in?

**Comment by craigcomstock** [comment]
@chr15m sounds good. I'll try that out. :+1:

**Comment by chr15m** [comment]
When pd-for-android is updated I will update this again.
