### ISSUE TITLE
Patches not read from storage

### ISSUE THREAD

**Issue by chr15m** [chr15m/PdDroidParty#55]
Reported by @Ant1r:

> Moreover, I downloaded 
> https://droidparty.net/patches/droidparty-demos.zip to my device, but 
> couldn't extract it to my newly created /PdDroidPart directory.
> 
> So I checked the zip file on my linux desktop, and I saw the archive 
> consists of a "../droidparty-demos/" directory; I believe that starting 
> with "../" is problematic.
> 
> Then I used my desktop to finally extract the zip, I placed the content 
> to the /PdDroidParty directory on my device, but PdDroidParty couldn't 
> find the patches ("PdDroidParty compatiblble patches found" is empty). 
> "adb logcat" shows:
> (...) PatchSelector: search path:/storage/emulated/0/PdDroidParty
> (...) PdDroidParty: PatchSelector.initPd: []
> 
> I also tried to create a "/sdcard/PdDroidParty" directory and copied the 
> "drum-machine" directory to there, but it couldn't be found either.

**Comment by chr15m** [comment]
@Ant1r I have a couple of questions to help diagnose this issue.

1. Is this the only mention of "search path" or are there others? `adb logcat | grep "search path"`

1. What is the result of the following command:

`adb ls /storage/emulated/0/`

**Comment by Ant1r** [comment]
1. no, sorry, nothing else...
2. : 
```
$ adb ls /storage/emulated/0/
000041f9 00000da0 6005c158 .
000041c9 00000da0 5febb5f1 ..
000041f9 00000da0 5fe4c19f MIUI
000041f9 00000da0 5fc56c81 Android
000081b0 00000002 5febb5f3 dctp
000041f9 00000da0 5f19a0c4 documents
000041f9 00000da0 5fe4d194 Movies
000041f9 00000da0 5fcf7dcf Music
000041f9 00000da0 60023a92 WhatsApp
000041f9 00000da0 5e4bacd1 Musique
000041f9 00000da0 5fcba59a Pictures
000041f9 00000da0 6002bd32 Fonts
000041f9 00005000 60040421 Download
000041f9 00000da0 6005be60 DCIM
000081b0 0000004a 5febb5f9 did
000041f9 00000da0 5e033725 MiVideoGlobal
000041f9 00000da0 5ef9ee99 X Air
000041f9 00000da0 5f12e2b9 joox_for_third
000041f9 00000da0 5e05df62 Snapseed
000041f9 00000da0 60041176 PdDroidParty
000041f9 00000da0 60040cb7 sdcard--
000041f9 00000da0 5e0b1a8f KineMaster

$ adb ls /storage/emulated/0/PdDroidParty
000041f9 00000da0 60041176 .
000041f9 00000da0 6005c158 ..
000041f9 00000da0 60040a21 drum-machine
000041f9 00000da0 60040a24 multibeat
000041f9 00000da0 60040a24 pure-widgets-demo
000041f9 00000da0 60040a58 vocoder-rjdj
000081b0 00017835 60040a58 testo.pdz

```

**Comment by chr15m** [comment]
Thanks, was there a prompt for permission to access storage?

**Comment by Ant1r** [comment]
yes there was (I just checked reinstalling).

**Comment by Ant1r** [comment]
my phone is on Android 10.
couldn't it be about the new "scoped storage" policy (https://developer.android.com/training/data-storage#scoped-storage)?
maybe it could be worth it to move the patches directory to the app specific external directory?

**Comment by chr15m** [comment]
@Ant1r good question. This seems more annoying for a user (more typing if they must create that directory) but I guess I'll have to do it. Maybe I should put in place a small web server like what PdParty does. :thinking:

**Comment by Ant1r** [comment]
I think the directory is created automatically.

Yeah the online patch repo would be great!

**Comment by Ant1r** [comment]
So I guess that `getExternalStorageDirectory()` should definitely be replaced by `getExternalFilesDir()` (which exists since API 8), referring to:
https://developer.android.com/reference/android/os/Environment#getExternalStorageDirectory()
https://developer.android.com/reference/android/content/Context#getExternalFilesDir(java.lang.String)

There's also the newer `getExternalFilesDirs()` since API 19, which could be used to search for the patches into multiple possible paths.

**Comment by chr15m** [comment]
Thanks @Ant1r. I read the docs today and I am utterly bamboozled. Will take a look at this again tomorrow.

**Comment by chr15m** [comment]
I'm so confused by this. So is it the case that Android 10 is breaking backwards compatability such that even if you ask for access to `/sdcard` and the user grants permission, access is still not given? This must break hundreds of apps which do the same thing.

**Comment by chr15m** [comment]
@Ant1r I've pushed a potential fix, version 345: https://droidparty.net/downloads
If you put your patches in `/storage/emulated/0/Android/data/cx.mccormick.pddroidparty/files/PATCH-NAME` the app should be able to find them now. Can you let me know if this works for you?

**Comment by Ant1r** [comment]
Victory!

```
PatchSelector: search path:/storage/emulated/0/Android/data/cx.mccormick.pddroidparty/files
PdDroidParty: PatchSelector.initPd: [/storage/emulated/0/Android/data/cx.mccormick.pddroidparty/files/pure-widgets-demo/droidparty_main.pd, /storage/emulated/0/Android/data/cx.mccormick.pddroidparty/files/drum-machine/droidparty_main.pd, /storage/emulated/0/Android/data/cx.mccormick.pddroidparty/files/multibeat/droidparty_main.pd, /storage/emulated/0/Android/data/cx.mccormick.pddroidparty/files/vocoder-rjdj/droidparty_main.pd]
01-23 12:27:48.725 27093 27132 E PatchSelector: search path:/storage/emulated/0/PdDroidParty
01-23 12:27:48.725 27093 27132 E PdDroidParty: PatchSelector.initPd: []
```

unfortunately (but that's another issue):
```
ActivityManager: Permission Denial: startForeground from pid=27093, uid=10296 requires android.permission.FOREGROUND_SERVICE
01-23 12:27:51.603  1790  4162 I ActivityManager: Process cx.mccormick.pddroidparty (pid 27093) has died: cch CRE

```

**Comment by chr15m** [comment]
Thanks for testing.
