### ISSUE TITLE
Manifest needs android.permission.FOREGROUND_SERVICE

### ISSUE THREAD

**Issue by Ant1r** [chr15m/PdDroidParty#59]
PdDroidParty currently crashes on  Android10:
`ActivityManager: Permission Denial: startForeground from pid=27093, uid=10296 requires android.permission.FOREGROUND_SERVICE`

Apparently, "apps that target Android 9 (API level 28) or higher and use foreground services must request the FOREGROUND_SERVICE permission" (refer to: https://stackoverflow.com/questions/52382710/permission-denial-startforeground-requires-android-permission-foreground-servic).

**Comment by chr15m** [comment]
Thanks for filing this. 👍

**Comment by Ant1r** [comment]
I can confirm that adding the FOREGROUND_SERVICE permission fixes that! 
PdDroidParty-debug is now working on my phone. But other issues will follow ;-)

**Comment by chr15m** [comment]
> I can confirm that adding the FOREGROUND_SERVICE permission fixes that!

Did you just do this by adding to the manifest?

**Comment by Ant1r** [comment]
yes, nothing else to do.

**Comment by chr15m** [comment]
There's a new debug build up on the site, thanks for reporting @Ant1r.
