### ISSUE TITLE
Pressing backspace to quit the current patch doesn't return to menu and freezes the app

### ISSUE THREAD

**Issue by Ant1r** [chr15m/PdDroidParty#60]
After a patch has been opened, you cannot return to the menu, and are forced to use Android "recent apps" dialog to swipe-out the app.
log:
```
01-23 14:19:31.167  3494  3494 E PdDroidParty: BEFORE
01-23 14:19:31.167  3494  3494 E PdDroidParty: onBackPressed fromSelector ddd
01-23 14:19:31.354  1790  4163 I ActivityManager: Killing 32638:com.android.providers.partnerbookmarks/u0a141 (adj 985): empty #17
01-23 14:19:31.371  1790  4163 W ActivityManager: Sending non-protected broadcast android.intent.action.APPLICATION_MESSAGE_UPDATE from system 2411:com.android.systemui/1000 pkg com.android.systemui. Callers=
01-23 14:19:31.508  1790  4460 I ActivityManager: Process cx.mccormick.pddroidparty (pid 3494) has died: fore TOP 
01-23 14:19:31.714  1790  1956 W ActivityManager: setHasOverlayUi called on unknown pid: 3494

```

update: I've seen it succeed once! But most of the time it freezes. Seems like a timing issue about the relaunching of PatchSelector.

**Comment by chr15m** [comment]
@Ant1r if you get a second to test this new version and let me know if it works as you'd expect, I'd very much appreciate that. :pray: 

https://droidparty.net/builds/PdDroidParty-debug-349.apk

**Comment by Ant1r** [comment]
Yeah, it works fine now.
First 🔙 press quits the patch and returns to the menu, second one quits the app.
Congrats!

**Comment by chr15m** [comment]
Thanks for checking @Ant1r!
