### ISSUE TITLE
PdDroidParty doesn't find any patch and crashes

### ISSUE THREAD

**Issue by Pollinopops** [chr15m/PdDroidParty#62]
Hello,

I'm trying to use PdDroidParty on my Sony Xperia XZ2 with Android 10.
I installed the latest version on the play store. On launch it asked for permission to access my folders. I accepted.
I then created a folder named PdDroidParty on my SD card but the app doesn't find anything. I tried moving it to the internal memory and same result.

It recognized the demo files when I put them in this folder Android>data>cx.mccormick.pddroidparty>files
It finds them even without the folder named PdDroidParty.

But if I launch the patch from this folder the app quits instantly. I tried with another phone and I get the exact same result.

Thank you for your help !

**Comment by chr15m** [comment]
Thanks for reporting this.

@Ant1r did you see this on your device?

**Comment by chr15m** [comment]
@Pollinopops is there any chance you know how to use `adb` so we can see the cause of the traceback?

**Comment by Pollinopops** [comment]
@chr15m I don't but I will try and install it in order to get a log file. Will report here as soon as I get results with adb.

**Comment by Ant1r** [comment]
> Thanks for reporting this.
> 
> @Ant1r did you see this on your device?

nope; I can install from the Play Store, copy patches to Android/data/cx.mccormick.pddroidparty/files, accept the permissions, and run successfully e.g drum-machine (I just can't quit the patch to return to menu, but that's a different issue, see #60).

**Comment by Pollinopops** [comment]
Okay so I tried again removing everything and it turns out it is my specific PD patch that breaks something. If I remove it for the folder then the example patch drum-machine works fine.
Thank you for your answers.
Other than that is it "normal" that the app only finds patches in Android/data/cx.mccormick.pddroidparty/files ?
This might be confusing as the website tells to put the patches on the SD card.

**Comment by chr15m** [comment]
@Pollinopops ok that is quite good news, thank you! If you want to share the patch I could diagnose why it is causing PdDroidParty's patch selector to crash.

You are right that the website info is not yet updated. I need to do that and also put some instructions on the landing screen of the app as to where to put patches. Thank you for the reminder!

**Comment by chr15m** [comment]
@Pollinopops I have just updated the website doc.

**Comment by Pollinopops** [comment]
Wow you sure are quick !
The patch selector works, it is juste my patch that crashes the app. It also crashes MobMuPlat if I try to launch it directly but works if I launch it via a mmp interface.

If you're curious as to why it crashes you can have a look. It's a patch to control Orac running on another device. I didn't make it but downloaded it from here [https://github.com/TheTechnobear/Orac/tree/master/OscClients](https://github.com/TheTechnobear/Orac/tree/master/OscClients) under pd-android.

**Comment by Ant1r** [comment]
@Pollinopops maybe it' s because this patch makes use of mrpeach's `routeOSC`. Did you add the source of `routeOSC` to your project's sources? Other way is that `routeOSC` could be avoided, since Pd vanilla now implements an `oscparse` that can do about the same job. Of course this would need reworking the patch (oscparse is not 'as-is' replacement for routeOSC).

**Comment by Pollinopops** [comment]
Thank you for the reply @Ant1r. The desktop version uses `routeOSC` but the android one under Pd-android already does it with `oscparse`.
